---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openproject.fullname" . | lower }}
type: Opaque
data:
  DATABASE_URL: "{{ include "openproject.databaseURI" . }}"
  {{- if .Values.memcached.enabled }}
  OPENPROJECT_CACHE__MEMCACHE__SERVER: "{{ include "openproject.memcached.fullname" . }}"
  {{- end }}
  {{- if and .Values.volumeMounts .Values.volumeMounts.mountPath }}
  OPENPROJECT_ATTACHMENTS__STORAGE__PATH: "{{ .Values.volumeMounts.mountPath }}"
  {{- end }}
  {{- with .Values.openProjectEnv }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
