
{{- define "openproject.databaseURL" -}}
{{- $a := (printf "%s%s%s%s%s%s%s%s%s%s" 
          "postgres://" 
          .Values.database.username ":"
          .Values.database.password "@"
          .Values.database.host ":"
          .Values.database.port "/"
          .Values.database.name ) -}}
  {{- if or .Values.database.pool .Values.database.encoding .Values.database.reconnect -}}
    {{- $a = (printf "%s%s" $a "?") -}}
    {{- if .Values.database.pool -}}
    {{- $a = (printf "%s%s%s" $a "pool="
                    .Values.database.pool ) -}}
    {{- end }}
    {{- if .Values.database.encoding }}
      {{- if .Values.database.pool -}}
        {{- $a = (printf "%s%s" $a "&" ) -}}
      {{- end -}}
      {{- $a = (printf "%s%s%s" $a "encoding=" 
                       .Values.database.encoding ) -}}
    {{- end }}
    {{- if .Values.database.reconnect }}
      {{- if or .Values.database.pool .Values.database.encoding -}}
        {{- $a = (printf "%s%s" $a "&" ) -}}
      {{- end -}}
      {{- $a = (printf "%s%s%s" $a "reconnect=" 
                       .Values.database.reconnect ) -}}
    {{- end }}
  {{- end }}
  {{- printf "%s" $a | b64enc }}
{{- end -}}

{{- if and .Values.database.host .Values.database.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openproject.fullname" . | lower }}
type: Opaque
data:
  DATABASE_URL: "{{ template "openproject.databaseURL" . }}"
  {{- /*
  DATABASE_USERNAME: "{{ .Values.database.username | b64enc }}"
  DATABASE_PASSWORD: "{{ .Values.database.password | b64enc }}"
  */}}
  RAILS_CACHE_STORE: {{ .Values.openProjectEnv.RAILS_CACHE_STORE | b64enc | quote }}
  OPENPROJECT_CACHE__MEMCACHE__SERVER: {{ .Values.openProjectEnv.CACHE__MEMCACHE__SERVER | b64enc | quote }}
  OPENPROJECT_RAILS__RELATIVE__URL__ROOT: {{ .Values.openProjectEnv.RAILS__RELATIVE__URL__ROOT | b64enc | quote }}
  RAILS_MIN_THREADS: {{ .Values.openProjectEnv.RAILS_MIN_THREADS | b64enc | quote }}
  RAILS_MAX_THREADS: {{ .Values.openProjectEnv.RAILS_MAX_THREADS | b64enc | quote }}
  USE_PUMA: {{ .Values.openProjectEnv.USE_PUMA | b64enc | quote }}
  IMAP_ENABLED: {{ .Values.openProjectEnv.IMAP_ENABLED | b64enc | quote }}
{{- end }}
