{{- define "openproject.databaseURI" -}}
  {{- $databaseURI := "" -}}
  {{- if and .Values.database.external (and .Values.database.host .Values.database.name) -}}
    {{- $databaseURI = (printf "%s%s%s%s%s%s%s%s%s%s"  
            "postgres://" 
            .Values.database.username ":"
            .Values.database.password "@"
            .Values.database.host ":"
            .Values.database.port "/"
            .Values.database.name ) -}}
    {{- if or .Values.database.pool .Values.database.encoding .Values.database.reconnect -}}
      {{- $databaseURI = (printf "%s%s" $databaseURI "?") -}}
      {{- if .Values.database.pool -}}
        {{- $databaseURI = (printf "%s%s%s" $databaseURI "pool="
                        .Values.database.pool ) -}}
      {{- end -}}
      {{- if .Values.database.encoding -}}
        {{- if .Values.database.pool -}}
          {{- $databaseURI = (printf "%s%s" $databaseURI "&" ) -}}
        {{- end -}}
        {{- $databaseURI = (printf "%s%s%s" $databaseURI "encoding=" 
                        .Values.database.encoding ) -}}
      {{- end -}}
      {{- if .Values.database.reconnect -}}
        {{- if or .Values.database.pool .Values.database.encoding -}}
          {{- $databaseURI = (printf "%s%s" $databaseURI "&" ) -}}
        {{- end -}}
        {{- $databaseURI = (printf "%s%s%s" $databaseURI "reconnect=" 
                        .Values.database.reconnect ) -}}
      {{- end -}}
    {{- end -}}
  {{- else -}}
    {{- $databaseURI = (printf "%s%s%s%s%s%s" 
            "postgresql://postgres:"
            .Values.postgresql.postgresqlPassword "@"
            (include "openproject.postgresql.fullname" . | lower ) "/"
            .Values.postgresql.postgresqlDatabase ) -}}
  {{- end -}}
  {{- printf "%s" $databaseURI | b64enc -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openproject.fullname" . | lower }}
type: Opaque
data:
  DATABASE_URL: "{{ template "openproject.databaseURI" . }}"
  OPENPROJECT_CACHE__MEMCACHE__SERVER: "{{ include "openproject.memcached.fullname" . }}"
  {{- with .Values.openProjectEnv }}
    {{- toYaml . | nindent 2 }}
  {{- end }}